TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 128
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 5
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /home/lsrock1/data/kinetics/
VOV3D:
  DEPTH: 31
  TRANS_FUNC: t_osa_2plus1_transform
  NUM_CONV: 5
  INNER_CH: 40
  TEMPORAL_DILATIONS: [[1], [1], [1], [1]]
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[1],[1],[1],[1]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  BASE_LR_SCALE_NUM_SHARDS: True
  MAX_EPOCH: 256
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 35.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 400
  ARCH: vov3d
  MODEL_NAME: VoV3D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
LOG_MODEL_INFO: True
TENSORBOARD:
  ENABLE: True
OUTPUT_DIR: output/K400/vov3d/vov3d_M
